-- This module is the root of the GeneralLanglandsFunctorialityCanonicalLaneLean Lean proof package.
import GeneralLanglandsFunctorialityCanonicalLaneLean.Basic
import GeneralLanglandsFunctorialityCanonicalLaneLean.SourcePackage
import GeneralLanglandsFunctorialityCanonicalLaneLean.SourceDependencies
import GeneralLanglandsFunctorialityCanonicalLaneLean.Formalization
import GeneralLanglandsFunctorialityCanonicalLaneLean.ReviewerBridge
import GeneralLanglandsFunctorialityCanonicalLaneLean.TheoremStatement
import GeneralLanglandsFunctorialityCanonicalLaneLean.MathlibStatement
